// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: services/queue/rpc/pb/queue/queue.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//创建订单队列
type OrderCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScreenId int64    `protobuf:"varint,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	Uid      int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount   int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Seat     []string `protobuf:"bytes,4,rep,name=seat,proto3" json:"seat,omitempty"`
}

func (x *OrderCreateRequest) Reset() {
	*x = OrderCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_queue_rpc_pb_queue_queue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateRequest) ProtoMessage() {}

func (x *OrderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_queue_rpc_pb_queue_queue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateRequest.ProtoReflect.Descriptor instead.
func (*OrderCreateRequest) Descriptor() ([]byte, []int) {
	return file_services_queue_rpc_pb_queue_queue_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreateRequest) GetScreenId() int64 {
	if x != nil {
		return x.ScreenId
	}
	return 0
}

func (x *OrderCreateRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OrderCreateRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderCreateRequest) GetSeat() []string {
	if x != nil {
		return x.Seat
	}
	return nil
}

type OrderCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderKey string `protobuf:"bytes,1,opt,name=order_key,json=orderKey,proto3" json:"order_key,omitempty"`
}

func (x *OrderCreateResponse) Reset() {
	*x = OrderCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_queue_rpc_pb_queue_queue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateResponse) ProtoMessage() {}

func (x *OrderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_queue_rpc_pb_queue_queue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateResponse.ProtoReflect.Descriptor instead.
func (*OrderCreateResponse) Descriptor() ([]byte, []int) {
	return file_services_queue_rpc_pb_queue_queue_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreateResponse) GetOrderKey() string {
	if x != nil {
		return x.OrderKey
	}
	return ""
}

//自动取消未支付订单队列
type OrderDelayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *OrderDelayRequest) Reset() {
	*x = OrderDelayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_queue_rpc_pb_queue_queue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDelayRequest) ProtoMessage() {}

func (x *OrderDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_queue_rpc_pb_queue_queue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDelayRequest.ProtoReflect.Descriptor instead.
func (*OrderDelayRequest) Descriptor() ([]byte, []int) {
	return file_services_queue_rpc_pb_queue_queue_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDelayRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderDelayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack int64 `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *OrderDelayResponse) Reset() {
	*x = OrderDelayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_queue_rpc_pb_queue_queue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDelayResponse) ProtoMessage() {}

func (x *OrderDelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_queue_rpc_pb_queue_queue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDelayResponse.ProtoReflect.Descriptor instead.
func (*OrderDelayResponse) Descriptor() ([]byte, []int) {
	return file_services_queue_rpc_pb_queue_queue_proto_rawDescGZIP(), []int{3}
}

func (x *OrderDelayResponse) GetAck() int64 {
	if x != nil {
		return x.Ack
	}
	return 0
}

var File_services_queue_rpc_pb_queue_queue_proto protoreflect.FileDescriptor

var file_services_queue_rpc_pb_queue_queue_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x22, 0x6f, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x61,
	0x74, 0x22, 0x32, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0x2e, 0x0a, 0x11, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65,
	0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x32, 0x8f, 0x01,
	0x0a, 0x05, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x19, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x18, 0x2e, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_services_queue_rpc_pb_queue_queue_proto_rawDescOnce sync.Once
	file_services_queue_rpc_pb_queue_queue_proto_rawDescData = file_services_queue_rpc_pb_queue_queue_proto_rawDesc
)

func file_services_queue_rpc_pb_queue_queue_proto_rawDescGZIP() []byte {
	file_services_queue_rpc_pb_queue_queue_proto_rawDescOnce.Do(func() {
		file_services_queue_rpc_pb_queue_queue_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_queue_rpc_pb_queue_queue_proto_rawDescData)
	})
	return file_services_queue_rpc_pb_queue_queue_proto_rawDescData
}

var file_services_queue_rpc_pb_queue_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_queue_rpc_pb_queue_queue_proto_goTypes = []interface{}{
	(*OrderCreateRequest)(nil),  // 0: queue.OrderCreateRequest
	(*OrderCreateResponse)(nil), // 1: queue.OrderCreateResponse
	(*OrderDelayRequest)(nil),   // 2: queue.OrderDelayRequest
	(*OrderDelayResponse)(nil),  // 3: queue.OrderDelayResponse
}
var file_services_queue_rpc_pb_queue_queue_proto_depIdxs = []int32{
	0, // 0: queue.Queue.OrderQueue:input_type -> queue.OrderCreateRequest
	2, // 1: queue.Queue.OrderDelay:input_type -> queue.OrderDelayRequest
	1, // 2: queue.Queue.OrderQueue:output_type -> queue.OrderCreateResponse
	3, // 3: queue.Queue.OrderDelay:output_type -> queue.OrderDelayResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_queue_rpc_pb_queue_queue_proto_init() }
func file_services_queue_rpc_pb_queue_queue_proto_init() {
	if File_services_queue_rpc_pb_queue_queue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_queue_rpc_pb_queue_queue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_queue_rpc_pb_queue_queue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_queue_rpc_pb_queue_queue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDelayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_queue_rpc_pb_queue_queue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDelayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_queue_rpc_pb_queue_queue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_queue_rpc_pb_queue_queue_proto_goTypes,
		DependencyIndexes: file_services_queue_rpc_pb_queue_queue_proto_depIdxs,
		MessageInfos:      file_services_queue_rpc_pb_queue_queue_proto_msgTypes,
	}.Build()
	File_services_queue_rpc_pb_queue_queue_proto = out.File
	file_services_queue_rpc_pb_queue_queue_proto_rawDesc = nil
	file_services_queue_rpc_pb_queue_queue_proto_goTypes = nil
	file_services_queue_rpc_pb_queue_queue_proto_depIdxs = nil
}
