// Code generated by goctl. DO NOT EDIT!
// Source: film.proto

package server

import (
	"context"

	"cinema-shop/services/film/rpc/internal/logic"
	"cinema-shop/services/film/rpc/internal/svc"
	"cinema-shop/services/film/rpc/pb/film"
)

type FilmServer struct {
	svcCtx *svc.ServiceContext
	film.UnimplementedFilmServer
}

func NewFilmServer(svcCtx *svc.ServiceContext) *FilmServer {
	return &FilmServer{
		svcCtx: svcCtx,
	}
}

// 影片列表
func (s *FilmServer) List(ctx context.Context, in *film.FilmListRequest) (*film.FilmListResponse, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

// 影片详情
func (s *FilmServer) Detail(ctx context.Context, in *film.FilmDatailRequest) (*film.FilmDetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}
