// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: services/cinema/rpc/pb/cinema/cinema.proto

package cinema

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CinemaClient is the client API for Cinema service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CinemaClient interface {
	//影片列表
	List(ctx context.Context, in *FilmListRequest, opts ...grpc.CallOption) (*FilmListResponse, error)
	//影片详情
	Detail(ctx context.Context, in *FilmDatailRequest, opts ...grpc.CallOption) (*FilmDetailResponse, error)
}

type cinemaClient struct {
	cc grpc.ClientConnInterface
}

func NewCinemaClient(cc grpc.ClientConnInterface) CinemaClient {
	return &cinemaClient{cc}
}

func (c *cinemaClient) List(ctx context.Context, in *FilmListRequest, opts ...grpc.CallOption) (*FilmListResponse, error) {
	out := new(FilmListResponse)
	err := c.cc.Invoke(ctx, "/cinema.Cinema/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cinemaClient) Detail(ctx context.Context, in *FilmDatailRequest, opts ...grpc.CallOption) (*FilmDetailResponse, error) {
	out := new(FilmDetailResponse)
	err := c.cc.Invoke(ctx, "/cinema.Cinema/Detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CinemaServer is the server API for Cinema service.
// All implementations must embed UnimplementedCinemaServer
// for forward compatibility
type CinemaServer interface {
	//影片列表
	List(context.Context, *FilmListRequest) (*FilmListResponse, error)
	//影片详情
	Detail(context.Context, *FilmDatailRequest) (*FilmDetailResponse, error)
	mustEmbedUnimplementedCinemaServer()
}

// UnimplementedCinemaServer must be embedded to have forward compatible implementations.
type UnimplementedCinemaServer struct {
}

func (UnimplementedCinemaServer) List(context.Context, *FilmListRequest) (*FilmListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCinemaServer) Detail(context.Context, *FilmDatailRequest) (*FilmDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detail not implemented")
}
func (UnimplementedCinemaServer) mustEmbedUnimplementedCinemaServer() {}

// UnsafeCinemaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CinemaServer will
// result in compilation errors.
type UnsafeCinemaServer interface {
	mustEmbedUnimplementedCinemaServer()
}

func RegisterCinemaServer(s grpc.ServiceRegistrar, srv CinemaServer) {
	s.RegisterService(&Cinema_ServiceDesc, srv)
}

func _Cinema_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilmListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CinemaServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cinema.Cinema/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CinemaServer).List(ctx, req.(*FilmListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cinema_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilmDatailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CinemaServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cinema.Cinema/Detail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CinemaServer).Detail(ctx, req.(*FilmDatailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cinema_ServiceDesc is the grpc.ServiceDesc for Cinema service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cinema_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cinema.Cinema",
	HandlerType: (*CinemaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Cinema_List_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _Cinema_Detail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/cinema/rpc/pb/cinema/cinema.proto",
}
