// Code generated by goctl. DO NOT EDIT!

package hall

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	hallFieldNames          = builder.RawFieldNames(&Hall{})
	hallRows                = strings.Join(hallFieldNames, ",")
	hallRowsExpectAutoSet   = strings.Join(stringx.Remove(hallFieldNames, "`hall_id`", "`create_time`", "`update_time`"), ",")
	hallRowsWithPlaceHolder = strings.Join(stringx.Remove(hallFieldNames, "`hall_id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheHallHallIdPrefix = "cache:hall:hallId:"
)

type (
	hallModel interface {
		Insert(ctx context.Context, data *Hall) (sql.Result, error)
		FindOne(ctx context.Context, hallId int64) (*Hall, error)
		Update(ctx context.Context, data *Hall) error
		Delete(ctx context.Context, hallId int64) error
	}

	defaultHallModel struct {
		sqlc.CachedConn
		table string
	}

	Hall struct {
		HallId   int64          `db:"hall_id"`   // 影厅ID
		Row      sql.NullInt64  `db:"row"`       // 行数
		Col      sql.NullInt64  `db:"col"`       // 列数
		Seat     sql.NullString `db:"seat"`      // 座位的矩阵【0不可用 1可用】
		CinemaId sql.NullInt64  `db:"cinema_id"` // 影院ID
		HallName sql.NullString `db:"hall_name"` // 影厅名称
	}
)

func newHallModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultHallModel {
	return &defaultHallModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`hall`",
	}
}

func (m *defaultHallModel) Insert(ctx context.Context, data *Hall) (sql.Result, error) {
	hallHallIdKey := fmt.Sprintf("%s%v", cacheHallHallIdPrefix, data.HallId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, hallRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Row, data.Col, data.Seat, data.CinemaId, data.HallName)
	}, hallHallIdKey)
	return ret, err
}

func (m *defaultHallModel) FindOne(ctx context.Context, hallId int64) (*Hall, error) {
	hallHallIdKey := fmt.Sprintf("%s%v", cacheHallHallIdPrefix, hallId)
	var resp Hall
	err := m.QueryRowCtx(ctx, &resp, hallHallIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `hall_id` = ? limit 1", hallRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, hallId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHallModel) Update(ctx context.Context, data *Hall) error {
	hallHallIdKey := fmt.Sprintf("%s%v", cacheHallHallIdPrefix, data.HallId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `hall_id` = ?", m.table, hallRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Row, data.Col, data.Seat, data.CinemaId, data.HallName, data.HallId)
	}, hallHallIdKey)
	return err
}

func (m *defaultHallModel) Delete(ctx context.Context, hallId int64) error {
	hallHallIdKey := fmt.Sprintf("%s%v", cacheHallHallIdPrefix, hallId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `hall_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, hallId)
	}, hallHallIdKey)
	return err
}

func (m *defaultHallModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheHallHallIdPrefix, primary)
}

func (m *defaultHallModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `hall_id` = ? limit 1", hallRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultHallModel) tableName() string {
	return m.table
}
