// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	ScreenId int64    `json:"screen_id"`
	SeatMap  []string `json:"seat_map"`
}

type OrderResp struct {
	OrderKey string `json:"order_key"`
}
