// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"cinema-shop/services/order/rpc/internal/logic"
	"cinema-shop/services/order/rpc/internal/svc"
	"cinema-shop/services/order/rpc/pb/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// 根据排片ID获取已被占用的座位
func (s *OrderServer) TicketSeat(ctx context.Context, in *order.TicketSeatRequest) (*order.TicketSeatResponse, error) {
	l := logic.NewTicketSeatLogic(ctx, s.svcCtx)
	return l.TicketSeat(in)
}
