// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Cinema "cinema-shop/services/cinema/api/internal/handler/Cinema"
	Film "cinema-shop/services/cinema/api/internal/handler/Film"
	Screen "cinema-shop/services/cinema/api/internal/handler/Screen"
	"cinema-shop/services/cinema/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list/:status/:page/:limit",
				Handler: Film.FilmListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail/:film_id",
				Handler: Film.FilmDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/film/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/screen_cinema_info",
				Handler: Screen.ScreenCinemaInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/screen_list",
				Handler: Screen.ScreenListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/screen/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cinema_detail",
				Handler: Cinema.CinemaDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/cinema/v1"),
	)
}
