// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginData struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshToken string `json:"refreshAfter"`
}

type LoginResp struct {
	Data    LoginData `json:"data"`
	ErrCode int       `json:"err_code"`
	ErrMsg  string    `json:"err_msg"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type RegisterData struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshToken string `json:"refreshAfter"`
}

type RegisterResp struct {
	Data    RegisterData `json:"data"`
	ErrCode int          `json:"err_code"`
	ErrMsg  string       `json:"err_msg"`
}

type RefreshTokenReq struct {
	RefToken string `json:"ref_token"`
}

type RefreshTokenData struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshToken string `json:"refreshAfter"`
}

type RefreshTokenResp struct {
	Data    RefreshTokenData `json:"data"`
	ErrCode int              `json:"err_code"`
	ErrMsg  string           `json:"err_msg"`
}

type GetUserInfoData struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type GetUserInfoResp struct {
	Data    GetUserInfoData `json:"data"`
	ErrCode int             `json:"err_code"`
	ErrMsg  string          `json:"err_msg"`
}
