// Code generated by goctl. DO NOT EDIT.
package types

type FilmListInfo struct {
	FilmId   int    `json:"film_id"`
	Type     int    `json:"type"`
	FilmName string `json:"film_name"`
	CoverPic string `json:"cover_pic"`
}

type FilmListInfoResp struct {
	Data  []FilmListInfo `json:"data"`
	Count int            `json:"count"`
	Page  int            `json:"page"`
}

type FilmListReq struct {
	Status int `path:"status"`
	Page   int `path:"page"`
	Limit  int `path:"limit"`
}

type FilmListResp struct {
	Data    FilmListInfoResp `json:"data"`
	ErrCode int              `json:"err_code"`
	ErrMsg  string           `json:"err_msg"`
}

type FilmDetailInfo struct {
	FilmId   int    `json:"film_id"`
	Cate     int    `json:"cate"`
	FilmName string `json:"film_name"`
	CoverPic string `json:"cover_pic"`
	FilmDesc string `json:"film_desc"`
}

type FilmDetailReq struct {
	FilmId int `path:"film_id"`
}

type FilmDetailResp struct {
	Data    FilmDetailInfo `json:"data"`
	ErrCode int            `json:"err_code"`
	ErrMsg  string         `json:"err_msg"`
}

type ScreenCinemaInfoReq struct {
	TDate    string `json:"t_date"`
	FilmId   int    `json:"film_id"`
	CityCode string `json:"city_code"`
	AreaCode string `json:"area_code"`
}

type ScreenCinemaInfo struct {
	CinemaName string `json:"cinema_name"`
	Place      string `json:"place"`
	Score      int    `json:"score"`
	Film       string `json:"film"`
	Tags       string `json:"tags"`
	Price      int    `json:"price"`
}

type ScreenCinemaInfoResp struct {
	Data    []ScreenCinemaInfo `json:"data"`
	ErrCode int                `json:"err_code"`
	ErrMsg  string             `json:"err_msg"`
}

type CinemaDetailReq struct {
	CinemaId int64 `json:"cinema_id"`
}

type FilmInfo struct {
	FilmId   int64  `json:"film_id"`
	FilmName string `json:"film_name"`
	Duration int64  `json:"duration"`
	CoverPic string `json:"cover_pic"`
	Cate     int64  `json:"cate"`
}

type CinemaDetailInfo struct {
	CinemaName string     `json:"cinema_name"`
	CinemaId   int64      `json:"cinema_id"`
	Place      string     `json:"place"`
	City       string     `json:"city"`
	Area       string     `json:"area"`
	Score      int64      `json:"score"`
	Tags       string     `json:"tags"`
	FilmInfos  []FilmInfo `json:"film_infos"`
}

type CinemaDatailResp struct {
	Data    CinemaDetailInfo `json:"data"`
	ErrCode int              `json:"err_code"`
	ErrMsg  string           `json:"err_msg"`
}
