// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package order

import (
	"context"

	"cinema-shop/services/order/rpc/pb/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderGenRequest    = order.OrderGenRequest
	OrderGenResponse   = order.OrderGenResponse
	OrderRequest       = order.OrderRequest
	OrderResponse      = order.OrderResponse
	TicketSeatRequest  = order.TicketSeatRequest
	TicketSeatResponse = order.TicketSeatResponse

	Order interface {
		// 根据排片ID获取已被占用的座位
		TicketSeat(ctx context.Context, in *TicketSeatRequest, opts ...grpc.CallOption) (*TicketSeatResponse, error)
		// 创建订单
		OrderCreate(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
		// 生成订单数据
		OrderGen(ctx context.Context, in *OrderGenRequest, opts ...grpc.CallOption) (*OrderGenResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// 根据排片ID获取已被占用的座位
func (m *defaultOrder) TicketSeat(ctx context.Context, in *TicketSeatRequest, opts ...grpc.CallOption) (*TicketSeatResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.TicketSeat(ctx, in, opts...)
}

// 创建订单
func (m *defaultOrder) OrderCreate(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.OrderCreate(ctx, in, opts...)
}

// 生成订单数据
func (m *defaultOrder) OrderGen(ctx context.Context, in *OrderGenRequest, opts ...grpc.CallOption) (*OrderGenResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.OrderGen(ctx, in, opts...)
}
