// Code generated by goctl. DO NOT EDIT!
// Source: cinema.proto

package cinema

import (
	"context"

	"cinema-shop/services/cinema/rpc/pb/cinema"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CinemaDetailRequest      = cinema.CinemaDetailRequest
	CinemaDetailResp         = cinema.CinemaDetailResp
	CinemaInfo               = cinema.CinemaInfo
	CinemaInfoRequest        = cinema.CinemaInfoRequest
	CinemaInfoResponse       = cinema.CinemaInfoResponse
	FilmAllRequest           = cinema.FilmAllRequest
	FilmAllResponse          = cinema.FilmAllResponse
	FilmDatailRequest        = cinema.FilmDatailRequest
	FilmDetailInfo           = cinema.FilmDetailInfo
	FilmDetailResponse       = cinema.FilmDetailResponse
	FilmInfo                 = cinema.FilmInfo
	FilmListInfo             = cinema.FilmListInfo
	FilmListRequest          = cinema.FilmListRequest
	FilmListResponse         = cinema.FilmListResponse
	HallInfo                 = cinema.HallInfo
	HallListRequest          = cinema.HallListRequest
	HallListResponse         = cinema.HallListResponse
	ScreenCinemaInfo         = cinema.ScreenCinemaInfo
	ScreenCinemaInfoRequest  = cinema.ScreenCinemaInfoRequest
	ScreenCinemaInfoResponse = cinema.ScreenCinemaInfoResponse
	ScreenFilmIdRequest      = cinema.ScreenFilmIdRequest
	ScreenFilmIdResponse     = cinema.ScreenFilmIdResponse
	ScreenInfo               = cinema.ScreenInfo
	ScreenListRequest        = cinema.ScreenListRequest
	ScreenListResponse       = cinema.ScreenListResponse

	Cinema interface {
		// 影片列表
		FilmList(ctx context.Context, in *FilmListRequest, opts ...grpc.CallOption) (*FilmListResponse, error)
		// 影片详情
		FilmDetail(ctx context.Context, in *FilmDatailRequest, opts ...grpc.CallOption) (*FilmDetailResponse, error)
		// 根据地理位置获取影院信息
		CinemaInfo(ctx context.Context, in *CinemaInfoRequest, opts ...grpc.CallOption) (*CinemaInfoResponse, error)
		// 根据影片和日期和影院ID获取排片信息
		ScreenCinemaInfo(ctx context.Context, in *ScreenCinemaInfoRequest, opts ...grpc.CallOption) (*ScreenCinemaInfoResponse, error)
		// 根据影院ID获取详情
		CinemaDetail(ctx context.Context, in *CinemaDetailRequest, opts ...grpc.CallOption) (*CinemaDetailResp, error)
		// 根据日期、影院ID获取排片电影
		ScreenFilmId(ctx context.Context, in *ScreenFilmIdRequest, opts ...grpc.CallOption) (*ScreenFilmIdResponse, error)
		// 根据影片ID获取全部影片信息
		FilmAll(ctx context.Context, in *FilmAllRequest, opts ...grpc.CallOption) (*FilmAllResponse, error)
		// 根据影院ID获取影厅列表
		HallList(ctx context.Context, in *HallListRequest, opts ...grpc.CallOption) (*HallListResponse, error)
		// 根据日期、影院ID、影片ID获取排片场次
		ScreenList(ctx context.Context, in *ScreenListRequest, opts ...grpc.CallOption) (*ScreenListResponse, error)
	}

	defaultCinema struct {
		cli zrpc.Client
	}
)

func NewCinema(cli zrpc.Client) Cinema {
	return &defaultCinema{
		cli: cli,
	}
}

// 影片列表
func (m *defaultCinema) FilmList(ctx context.Context, in *FilmListRequest, opts ...grpc.CallOption) (*FilmListResponse, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.FilmList(ctx, in, opts...)
}

// 影片详情
func (m *defaultCinema) FilmDetail(ctx context.Context, in *FilmDatailRequest, opts ...grpc.CallOption) (*FilmDetailResponse, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.FilmDetail(ctx, in, opts...)
}

// 根据地理位置获取影院信息
func (m *defaultCinema) CinemaInfo(ctx context.Context, in *CinemaInfoRequest, opts ...grpc.CallOption) (*CinemaInfoResponse, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.CinemaInfo(ctx, in, opts...)
}

// 根据影片和日期和影院ID获取排片信息
func (m *defaultCinema) ScreenCinemaInfo(ctx context.Context, in *ScreenCinemaInfoRequest, opts ...grpc.CallOption) (*ScreenCinemaInfoResponse, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.ScreenCinemaInfo(ctx, in, opts...)
}

// 根据影院ID获取详情
func (m *defaultCinema) CinemaDetail(ctx context.Context, in *CinemaDetailRequest, opts ...grpc.CallOption) (*CinemaDetailResp, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.CinemaDetail(ctx, in, opts...)
}

// 根据日期、影院ID获取排片电影
func (m *defaultCinema) ScreenFilmId(ctx context.Context, in *ScreenFilmIdRequest, opts ...grpc.CallOption) (*ScreenFilmIdResponse, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.ScreenFilmId(ctx, in, opts...)
}

// 根据影片ID获取全部影片信息
func (m *defaultCinema) FilmAll(ctx context.Context, in *FilmAllRequest, opts ...grpc.CallOption) (*FilmAllResponse, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.FilmAll(ctx, in, opts...)
}

// 根据影院ID获取影厅列表
func (m *defaultCinema) HallList(ctx context.Context, in *HallListRequest, opts ...grpc.CallOption) (*HallListResponse, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.HallList(ctx, in, opts...)
}

// 根据日期、影院ID、影片ID获取排片场次
func (m *defaultCinema) ScreenList(ctx context.Context, in *ScreenListRequest, opts ...grpc.CallOption) (*ScreenListResponse, error) {
	client := cinema.NewCinemaClient(m.cli.Conn())
	return client.ScreenList(ctx, in, opts...)
}
