// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Order "cinema-shop/services/order/api/internal/handler/Order"
	"cinema-shop/services/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: Order.OrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/order/v1"),
	)
}
