// Code generated by goctl. DO NOT EDIT!

package orders

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderFieldNames          = builder.RawFieldNames(&Order{})
	orderRows                = strings.Join(orderFieldNames, ",")
	orderRowsExpectAutoSet   = strings.Join(stringx.Remove(orderFieldNames, "`order_id`", "`create_time`", "`update_time`"), ",")
	orderRowsWithPlaceHolder = strings.Join(stringx.Remove(orderFieldNames, "`order_id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheOrderOrderIdPrefix = "cache:order:orderId:"
)

type (
	orderModel interface {
		Insert(ctx context.Context, data *Order) (sql.Result, error)
		FindOne(ctx context.Context, orderId int64) (*Order, error)
		Update(ctx context.Context, data *Order) error
		Delete(ctx context.Context, orderId int64) error
	}

	defaultOrderModel struct {
		sqlc.CachedConn
		table string
	}

	Order struct {
		OrderId   int64          `db:"order_id"`   // 订单ID
		OrderSn   sql.NullString `db:"order_sn"`   // 订单编号
		ScreenId  sql.NullInt64  `db:"screen_id"`  // 排片ID
		CreatedAt sql.NullTime   `db:"created_at"` // 创建时间
		Uid       sql.NullInt64  `db:"uid"`        // 用户ID
		UpdatedAt sql.NullTime   `db:"updated_at"` // 更新时间
		Amount    sql.NullInt64  `db:"amount"`     // 订单金额
		PayTime   sql.NullTime   `db:"pay_time"`   // 支付时间
		Status    sql.NullInt64  `db:"status"`     // 订单状态【1待支付 2支付完成 3检票成功 4已退票 5自动取消 6已过期】
	}
)

func newOrderModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultOrderModel {
	return &defaultOrderModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`order`",
	}
}

func (m *defaultOrderModel) Insert(ctx context.Context, data *Order) (sql.Result, error) {
	orderOrderIdKey := fmt.Sprintf("%s%v", cacheOrderOrderIdPrefix, data.OrderId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OrderSn, data.ScreenId, data.CreatedAt, data.Uid, data.UpdatedAt, data.Amount, data.PayTime, data.Status)
	}, orderOrderIdKey)
	return ret, err
}

func (m *defaultOrderModel) FindOne(ctx context.Context, orderId int64) (*Order, error) {
	orderOrderIdKey := fmt.Sprintf("%s%v", cacheOrderOrderIdPrefix, orderId)
	var resp Order
	err := m.QueryRowCtx(ctx, &resp, orderOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `order_id` = ? limit 1", orderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, orderId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) Update(ctx context.Context, data *Order) error {
	orderOrderIdKey := fmt.Sprintf("%s%v", cacheOrderOrderIdPrefix, data.OrderId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `order_id` = ?", m.table, orderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OrderSn, data.ScreenId, data.CreatedAt, data.Uid, data.UpdatedAt, data.Amount, data.PayTime, data.Status, data.OrderId)
	}, orderOrderIdKey)
	return err
}

func (m *defaultOrderModel) Delete(ctx context.Context, orderId int64) error {
	orderOrderIdKey := fmt.Sprintf("%s%v", cacheOrderOrderIdPrefix, orderId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `order_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, orderId)
	}, orderOrderIdKey)
	return err
}

func (m *defaultOrderModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheOrderOrderIdPrefix, primary)
}

func (m *defaultOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `order_id` = ? limit 1", orderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderModel) tableName() string {
	return m.table
}
